#![forbid(unsafe_code)]

mod environment;
mod game;
mod identity;
mod installation;
mod mods;
mod paths;
mod providers;

pub use environment::EnvironmentName;
pub use environment::EnvironmentRoot;
pub use environment::EnvironmentSchemaVersion;
pub use environment::InvalidEnvironmentName;
pub use environment::InvalidEnvironmentRoot;
pub use environment::UnsupportedEnvironmentSchemaVersion;
pub use game::GameBinding;
pub use game::GameInstallationPath;
pub use game::InvalidGameInstallationPath;
pub use game::InvalidSteamBuildId;
pub use game::SteamAppId;
pub use game::SteamBuildId;
pub use game::UnsupportedSteamAppId;
pub use identity::case_fold_key;
pub use installation::ArchiveIdentity;
pub use installation::ArchivePath;
pub use installation::FileDependencyState;
pub use installation::FomodCardinality;
pub use installation::FomodChoice;
pub use installation::FomodCondition;
pub use installation::InstallCandidate;
pub use installation::InstallCandidateOrigin;
pub use installation::InstallationPhase;
pub use installation::InvalidArchivePath;
pub use installation::InvalidSha256Digest;
pub use installation::OptionFileTrigger;
pub use installation::ResolvedOptionType;
pub use installation::Sha256Digest;
pub use mods::InstalledMod;
pub use mods::InvalidModName;
pub use mods::ModName;
pub use mods::ModPriority;
pub use paths::DataRelativePath;
pub use paths::InvalidDataRelativePath;
pub use providers::ParticipationReason;
pub use providers::ProviderClass;
pub use providers::ProviderReference;
