[package]
name = "infrastructure"
version = "0.0.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
environment = { path = "../environment", version = "0.0.0" }
settings = { path = "../settings", version = "0.0.0" }
game-platform = { path = "../game_platform", version = "0.0.0" }
archive = { path = "../archive", version = "0.0.0" }
execution = { path = "../execution", version = "0.0.0" }
application = { workspace = true }
domain = { workspace = true }
