[package]
name = "infrastructure-dependencies"
version = "0.2.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
infrastructure-nexus = { path = "../nexus" }
infrastructure-environment = { path = "../environment" }
infrastructure-settings = { path = "../settings" }
infrastructure-game-platform = { path = "../game_platform" }
infrastructure-archive = { path = "../archive" }
infrastructure-execution = { path = "../execution" }
application = { workspace = true }
domain = { workspace = true }
rootcause = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
