use crate::errors::ErrorMarker;
use rootcause::Result;
use std::future::Future;
use std::pin::Pin;

mod archive;
mod environment;
mod execution;
mod game_platform;
mod progress;
mod settings;
pub use archive::ExtractApprovedFiles;
pub use archive::IndexArchive;
pub use environment::AssessInitializationTarget;
pub use environment::AssessInstallation;
pub use environment::BeginInstallation;
pub use environment::BeginInstallationFile;
pub use environment::FinishInstallationChange;
pub use environment::FinishInstallationFile;
pub use environment::InitializationPlan;
pub use environment::InitializationProfileSources;
pub use environment::InitializationTargetAssessment;
pub use environment::InstallationChange;
pub use environment::InstallationFile;
pub use environment::InstallationStateAccess;
pub use environment::LoadInstallationState;
pub use environment::ProfileFileDisposition;
pub use environment::ProfileFileRecord;
pub use environment::ProfileSource;
pub use environment::PublishEnvironment;
pub use environment::ReadConflictContent;
pub use environment::ScanEnvironmentConflicts;
pub use environment::WriteInstallationChunk;
pub use execution::AdapterState;
pub use execution::CheckProfileState;
pub use execution::CloseVirtualFileSystem;
pub use execution::CreateVirtualFileSystem;
pub use execution::ExecutionProfile;
pub use execution::ExecutionProfileProjection;
pub use execution::FinishProgramOutput;
pub use execution::LaunchPlan;
pub use execution::LaunchProgram;
pub use execution::LaunchProvider;
pub use execution::LaunchTarget;
pub use execution::PrepareLaunchPlan;
pub use execution::PreserveExecutionProfile;
pub use execution::ProfileWarning;
pub use execution::ProgramExit;
pub use execution::ProgramOutput;
pub use execution::ProgramSupervision;
pub use execution::ProjectExecutionProfile;
pub use execution::ResolveLaunchTarget;
pub use execution::RunningProgram;
pub use execution::StageExecutionProfile;
pub use execution::StagedExecutionProfile;
pub use execution::SuperviseProgram;
pub use execution::VirtualFileSystem;
pub use game_platform::GameInstallationSource;
pub use game_platform::LoadProfileSources;
pub use game_platform::ReadGameVersion;
pub use game_platform::ReadXnvseVersion;
pub use game_platform::ResolveGameInstallation;
pub use game_platform::ResolvedGameInstallation;
pub use game_platform::ValidateEffectiveBinding;
pub use game_platform::ValidateGameDirectory;
pub use game_platform::ValidateGameInstallation;
pub use progress::ProgressEvent;
pub use progress::ReportProgress;
pub use settings::CheckSettingsReadiness;
pub use settings::PreviewGameBinding;
pub use settings::ReadInitializationGameOverride;
pub use settings::StoreGameBinding;
pub use settings::StoredAndEffectiveBinding;

pub type PortFuture<T, ErrorContext = ErrorMarker> = Pin<Box<dyn Future<Output = Result<T, ErrorContext>> + Send>>;
