[package]
name = "settings"
version = "0.0.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
application = { workspace = true }
cap-std = { workspace = true }
config = { version = "0.15.25", default-features = false, features = ["toml"] }
domain = { workspace = true }
encoding_rs = { workspace = true }
rootcause = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio-util = { workspace = true, features = ["rt"] }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Globalization", "Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile = { workspace = true }
