[package]
name = "environment"
version = "0.0.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
application = { path = "../../application", version = "0.0.0" }
domain = { path = "../../domain", version = "0.0.0" }
cap-fs-ext = "3.4.6"
cap-std = "3.4.6"
encoding_rs = "0.8.41"
rootcause = "0.13.0"
same-file = "1.0.6"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = { version = "0.11.0", default-features = false }
toml = "0.9.12"
tokio = { version = "1.53.1", features = ["sync"] }
tokio-util = { version = "0.7.19", features = ["rt"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
	"Win32_Foundation",
	"Win32_Globalization",
	"Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile = "3.27.0"
