[package]
name = "execution"
version = "0.0.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
application = { workspace = true }
domain = { workspace = true }
rootcause = { workspace = true }
sha2 = { workspace = true }
os_pipe = "1.2.3"
tempfile = { workspace = true }
uuid = { version = "1.26.1", features = ["v4"] }
tokio = { workspace = true, features = ["rt", "time", "sync", "macros"] }
tokio-util = { workspace = true }

[build-dependencies]
bindgen = "0.72.1"
cc = "1.4.7"
sha2 = { workspace = true }

[target."cfg(windows)".dependencies]
windows = { workspace = true, features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_JobObjects", "Win32_Security", "Win32_Storage_FileSystem", "Win32_System_Console"] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
