[package]
name = "application"
version = "0.0.0"
edition = "2024"
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
domain = { workspace = true }
rootcause = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }
tokio-util = { workspace = true, features = ["rt"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
